# Generated by Django 5.0 on 2024-06-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptree',
            name='major',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='adaptree',
            name='name',
            field=models.TextField(),
        ),
    ]
