# Generated by Django 5.0 on 2024-06-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academia', '0002_alter_academia_major_alter_academia_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academia',
            name='major',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='academia',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
