# Generated by Django 5.0 on 2024-06-28 17:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academia', '0003_alter_academia_major_alter_academia_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academia',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), size=None),
        ),
    ]
