# Generated by Django 5.0 on 2024-06-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academia', '0004_alter_academia_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academia',
            name='interests',
            field=models.TextField(null=True),
        ),
    ]
