# Generated by Django 5.0 on 2024-06-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academia', '0005_alter_academia_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academia',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academia',
            name='major',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academia',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
